# Generated by Django 3.2.1 on 2022-01-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliveModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alivescan',
            name='isShown',
            field=models.BooleanField(default=False),
        ),
    ]
