# Generated by Django 3.2.1 on 2022-01-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliveModel', '0002_alivescan_isshown'),
    ]

    operations = [
        migrations.AddField(
            model_name='alivescan',
            name='group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alivescan',
            name='mode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
